IF OBJECT_ID (N'dbo.HISTORICO_JUGADAS', N'U') IS NULL
	BEGIN
		CREATE TABLE HISTORICO_JUGADAS (
			HJUUNI BIGINT IDENTITY(1,1), 
			HJUJNI UNIQUEIDENTIFIER NOT NULL, --IDENTIFICADOR DE PARTIDA
			HJURSL CHAR(1) NOT NULL DEFAULT '', --RESULTADO (E) EMTARE  (H) JUGADOR 1 (C) JUGADOR 2
			HJUJUH CHAR(1) NOT NULL DEFAULT '', -- JUGADA JUGADOR 1 (P) PIEDRA (L) PAPEL (T) TIJERA
			HJUJUC CHAR(1) NOT NULL DEFAULT '', --JUGADA 2
			HJUUSP NVARCHAR(10) NOT NULL DEFAULT '', --JUGADOR 1
			HJUUSS NVARCHAR(10) NOT NULL DEFAULT '', --JUGADOR 2
			PRIMARY KEY (HJUUNI)
		) 
	END
GO

IF OBJECT_ID (N'dbo.JUEGOSGANADOS', N'U') IS NULL
	BEGIN
		CREATE TABLE JUEGOSGANADOS (
			JGNUNI BIGINT IDENTITY(1,1), 
			JGNUSR NVARCHAR(10) NOT NULL DEFAULT '', 
			PRIMARY KEY (JGNUNI)
		) 
	END
GO
